entity_delete_op.settings:
  type: config_object
  label: 'Entity delete op settings'
  mapping:
    delete_label:
      type: text
      label: 'The delete label operation'
    restore_label:
      type: text
      label: 'The restore label past operation'
    delete_label_past:
      type: text
      label: 'The delete label past operation'
    restore_label_past:
      type: text
      label: 'The restore label past operation'
    purge_label:
      type: text
      label: 'The purge label operation'
    purge_label_past:
      type: text
      label: 'The purge label past operation'
    purge_label_future:
      type: text
      label: 'The purge label future operation'
    label_base_field:
      type: text
      label: 'The label base field'
    label_restore_operation:
      type: text
      label: 'The label restore operation'
    label_delete_operation:
      type: text
      label: 'The label delete operation'
    label_purge_operation:
      type: text
      label: 'The label purge operation'
